name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test talisman
        uses: ./
        with:
          args: refs/heads/main ${{ github.event.after }} refs/heads/main ${{ github.event.before }}
